# undef DMENU_TOPBAR
# undef DMENU_FONTS
# undef DMENU_FOREGROUND
# undef DMENU_BACKGROUND
# undef DMENU_SELFOREGROUND
# undef DMENU_SELBACKGROUND
# undef DMENU_OUTFOREGROUND
# undef DMENU_OUTBACKGROUND
